name: Development

on: [push, pull_request]

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - "3.1"
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - uses: kurocha/setup-cpp@master
    
    - name: Git credentials
      run: |
        git config --global user.email "samuel@oriontransfer.net"
        git config --global user.name "Samuel Williams"
    
    - name: Run tests
      timeout-minutes: 5
      run: |
        gem install teapot
        teapot fetch
        teapot build Test/UnitTest
